config/routes.rb
Workshops::Application.routes.draw do
  use_doorkeeper

  mount RailsAdmin::Engine => '/admin', :as => 'admin'

  root to: 'homes#show'

  get '/api/v1/me.json' => 'api/v1/users#show', as: :resource_owner
  namespace :api do
    namespace :v1 do
      resources :completions, only: [:index, :show, :create, :destroy]
    end
  end

  get '/pages/tmux' => redirect('/products/4-humans-present-tmux')

  if Rails.env.staging? || Rails.env.production?
    get '/products/:id' => redirect('/workshops/18-test-driven-rails'),
      constraints: { id: /(10|12).*/ }
    get '/products/:id' => redirect('/workshops/19-design-for-developers'),
      constraints: { id: /(9|11).*/ }
    get '/products/14' => redirect('/prime')
    get '/products/14-prime' => redirect('/prime')
  end

  resource :session, controller: 'sessions'

  resources :sections, only: [] do
    resources :purchases, only: [:new, :create]
    resources :redemptions, only: [:new]
  end

  get '/courses.json' => redirect('/workshops.json')
  get '/courses/:id' => redirect('/workshops/%{id}')
  resources :workshops, only: [:index, :show] do
    resources :follow_ups, only: [:create]
  end

  resources :products, only: [:index, :show] do
    resources :redemptions, only: [:new]
    resources :stripe_redemptions, only: [:new]
    resources :purchases, only: [:new, :create]
  end
  get '/products/:id/purchases/:lookup' => redirect("/purchases/%{lookup}")

  resources :purchases, only: [:show] do
    resources :videos, only: [:show]
    member do
      get 'paypal'
    end
  end

  namespace :subscriber do
    resources :products, only: [] do
      resources :purchases, only: [:new, :create]
    end
    resources :sections, only: [] do
      resources :purchases, only: [:new, :create]
    end
    resources :invoices, only: [:index, :show]
  end

  resources :subscriptions, only: [:destroy, :update]

  resources :episodes, path: 'podcast', only: [:index, :show]
  get '/podcasts' => redirect("/podcast")
  get '/podcasts/:id' => redirect("/podcast/%{id}")

  resources :design_for_developers_resources, path: 'design-for-developers-resources', only: [:index, :show]
  resources :test_driven_rails_resources, path: 'test-driven-rails-resources', only: [:index]
  get '/d4d-resources' => redirect('/design-for-developers-resources')

  resources :topics, only: :index, path: 'trails'

  resources :bytes, only: [:index, :show]
  get '/articles/:id' => redirect("/bytes/%{id}")

  namespace :reports do
    resource :purchases_charts, only: :show
  end

  get '/auth/:provider/callback', to: 'auth_callbacks#create'

  get "/pages/*id" => 'pages#show', :as => :page, :format => false
  get '/prime' => 'pages#show', as: :prime, id: 'prime'
  get '/sale' => 'pages#show', as: :learnsale, id: 'learnsale'
  get '/watch' => 'pages#show', as: :watch, id: 'watch'
  get '/privacy' => 'pages#show', as: :privacy, id: 'privacy'
  get '/terms' => 'pages#show', as: :terms, id: 'terms'
  get '/directions' => "pages#show", as: :directions, id: "directions"
  get '/group-training' => "pages#show", as: :group_training, id: "group-training"
  get '/humans-present/oss' => "pages#show", as: :humans_present_oss, id: "humans-present-oss"
  get '/backbone-js-on-rails' => redirect("/products/1-backbone-js-on-rails")
  get '/5by5' => redirect('/workshops/19-design-for-developers?utm_source=5by5')
  get '/rubyist-booster-shot' => "pages#show", as: :rubyist_booster_shot, id: "rubyist-booster-shot"

  put '/my_account' => 'users#update', as: 'my_account'
  get '/my_account' => 'users#edit', as: 'my_account'
  get '/sign_up' => 'users#new', as: 'sign_up'
  get '/sign_in' => 'sessions#new', as: 'sign_in'
  resources :users, controller: 'users'
  resources :passwords, controller: 'passwords'

  mount Split::Dashboard, at: 'split'

  mount StripeEvent::Engine, at: 'stripe-webhook'

  resources 'bytes', only: :index

  get ':id' => 'topics#show', as: :topic
  get '/:id/articles' => 'articles#index', as: 'topic_articles'
  get '/:topic_id/bytes' => 'topics/bytes#index', as: 'topic_bytes'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  # Attributes
  attr_accessible :featured, :keywords, :name, :summary,
    :related_topic_ids

  # Associations
  has_many :articles, through: :classifications, source: :classifiable,
    source_type: 'Article'
  has_many :bytes, through: :classifications, source: :classifiable,
    source_type: 'Byte'
  has_many :classifications
  has_many :workshops, through: :classifications, source: :classifiable,
    source_type: 'Workshop'
  has_many :episodes, through: :classifications, source: :classifiable,
    source_type: 'Episode'
  has_many :products, through: :classifications, source: :classifiable,
    source_type: 'Product'
  has_many :topics, through: :classifications, source: :classifiable,
    source_type: 'Topic'
  has_one :trail

  # Validations
  validates :name, presence: true
  validates :slug, presence: true, uniqueness: true

  # Callbacks
  before_validation :generate_slug, on: :create

  def self.top
    featured.order('count DESC').limit 20
  end

  def self.featured
    where(featured: true)
  end

  def self.import_trail_maps
    featured.find_each do |topic|
      topic.import_trail_map
    end
  end

  def self.meta_keywords
    pluck(:name).join(', ')
  end

  def to_param
    slug
  end

  def related
    @related ||= Related.new(self)
  end

  def import_trail_map
    if trail
      trail.import
    end
  end

  private

  def generate_slug
    if name
      self.slug = CGI::escape(name.strip).downcase
    end
  end
end

app/controllers/topics/bytes_controller.rb
class Topics::BytesController < ApplicationController
  def index
    @topic = Topic.find_by_slug!(params[:topic_id])
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.top
  end

  def show
    @topic = Topic.find_by_slug!(params[:id])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def format_content(content, options = {} )
    length = options[:length] || 140
    omission = options[:omission] || '&#8230;'
    strip_tags(content).truncate(length, separator:' ', omission: omission)
  end

  def topic_classes(topics)
    topics.pluck(:slug).map(&:parameterize).join(' ')
  end
end

app/views/topics/_meta-info.html.erb
<section class='meta-info'>
  <p class='related'>Popular Topics:</p>

  <ul class='topics'>
    <% Topic.limit(20).each do |topic| %>
      <li><%= link_to topic.name_with_count, topic %></li>
    <% end %>
  </ul>
</section>

app/views/topics/_related.html.erb
<aside>
  <h3><%= t '.products' %></h3>
  <hr>
  <ul class='related-products related-workshops'>
    <% if subscription_product %>
      <li class="prime">
        <%= link_to prime_path do %>
          <span class="icon"><%= t('shared.subscriptions.icon') %></span>
          <hgroup>
          <h4>Access all of our products by subscribing to <%= subscription_product.name %></h4>
          </hgroup>
        <% end %>
      </li>
    <% end %>
    <%= render partial: 'topics/workshop', collection: @workshops %>
    <%= render partial: 'topics/product', collection: @products %>
  </ul>
</aside>

app/views/topics/_smart_app_banner.html.erb
<% content_for :meta do %>
  <%= tag(
    :meta,
    name: 'apple-itunes-app',
    content:"app-id=605401428, app-argument=#{url_for(only_path: false)}"
  ) %>
<% end %>

app/views/topics/_topic.html.erb
<div class="trail-category">
  <%= link_to topic_path(topic) do %>
    <section class="trail-info">
      <h2>Learn <%= topic.name %></h2>
      <% if topic.summary? %>
        <p><em><%= topic.summary %></em></p>
      <% end %>
    </section>
    <% if topic.trail %>
      <%= render 'trails/progress', trail: topic.trail %>
    <% end %>
  <% end %>
</div>

app/views/topics/_trail.html.erb
<div class="contribute">
  <%= link_to image_tag('contribute.png'), trail.contribute_url %>
</div>

<%= content_tag :section,
  :class => 'steps-complete',
  'data-trail-name' => trail.name,
  'data-complete' => '',
  'data-total' => trail.total do %>
  <div class="dots">
    <% trail.steps.each do |step| %>
      <% if step['resources'] %>
        <% step['resources'].each do |resource| %>
          <figure data-id="<%= resource['id'] %>" class="trail-bullet"></figure>
        <% end %>
      <% end %>
      <% if step['validations'] %>
        <% step['validations'].each do |validation| %>
          <figure data-id="<%= validation['id'] %>" class="trail-bullet"></figure>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

<section class="all-trail-map-steps">
  <div class="gutter-sizer"></div>
  <% trail.trail_map['steps'].each do |step| %>
    <section class='trail-map-steps' data-name="<%= trail.name %>">
      <% if step['name'] == 'Ongoing Reference' %>
        <h2 class="ongoing"><%= step['name'] %></h2>
      <% else %>
        <h2><%= step['name'] %></h2>
      <% end %>
      <% if step['resources'].present? %>
        <h3><%= t '.resources' %></h3>
        <ul>
          <% step['resources'].each do |resource| %>
            <li class="resource">
              <%= check_box_tag resource['id'] %>
              <div class="trail-bullet-hit-area">
                <div class="trail-bullet"></div>
              </div>
              <% if resource['uri'].present? %>
                <span><%= link_to(resource['title'], resource['uri']) %></span>
              <% else %>
                <span><%= resource['title'] %></span>
              <% end %>
            </li>
          <% end %>
        </ul>
      <% end %>
      <% if step['validations'].present? %>
        <h3><%= t '.validations' %></h3>
        <ul>
          <% step['validations'].each do |validation| %>
            <li class="validation">
              <% if validation.is_a? Hash %>
                <%= check_box_tag validation['id'] %>
                <div class="trail-bullet-hit-area">
                  <div class="trail-bullet"></div>
                </div>
                <span><%= link_to_if(validation['uri'].present?, validation['title'], validation['uri']) %></span>
              <% else %>
                <%= validation %>
              <% end %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </section>
  <% end %>
</section>

app/views/topics/index.html.erb
<%= render 'smart_app_banner' %>

<section class="trail-categories" id="topics-list">
  <%= render topics %>
</section 

app/views/topics/show.html.erb
<% content_for :meta_description, @topic.summary %>
<% content_for :meta_keywords, @topic.keywords %>
<% content_for :page_title, "Learn #{@topic.name}" %>
<% content_for :subject, @topic.name %>
<%= render 'smart_app_banner' %>

<% content_for :additional_header_links do %>
  <li class="all-trails"><%= link_to 'All Trails', topics_path %></li>
<% end %>

<% if @topic.summary.present? %>
  <div class="summary">
    <p><%= @topic.summary %></p>
    <% if @topic.related.topics.present? %>
      <p class="related-topics">
        Related topics:
        <%= render partial: 'relateds/topic', collection: @topic.related.topics %>
      </p>
    <% end %>
  </div>
<% end %>

<% if @topic.trail %>
  <%= render @topic.trail %>
<% end %>

<div class="related-reading">
  <% if @topic.articles.present? %>
    <p><%= link_to 'View related Giant Robots articles &rarr;'.html_safe, topic_articles_path(@topic) %></p>
  <% end %>
  <% if @topic.bytes.present? %>
    <p><%= link_to 'View related Prime Bytes &rarr;'.html_safe, topic_bytes_path(@topic) %></p>
  <% end %>
</div>

<%= render @topic.related %>