config/routes.rb
Workshops::Application.routes.draw do
  use_doorkeeper

  mount RailsAdmin::Engine => '/admin', :as => 'admin'

  root to: 'homes#show'

  get '/api/v1/me.json' => 'api/v1/users#show', as: :resource_owner
  namespace :api do
    namespace :v1 do
      resources :completions, only: [:index, :show, :create, :destroy]
    end
  end

  get '/pages/tmux' => redirect('/products/4-humans-present-tmux')

  if Rails.env.staging? || Rails.env.production?
    get '/products/:id' => redirect('/workshops/18-test-driven-rails'),
      constraints: { id: /(10|12).*/ }
    get '/products/:id' => redirect('/workshops/19-design-for-developers'),
      constraints: { id: /(9|11).*/ }
    get '/products/14' => redirect('/prime')
    get '/products/14-prime' => redirect('/prime')
  end

  resource :session, controller: 'sessions'

  resources :sections, only: [] do
    resources :purchases, only: [:new, :create]
    resources :redemptions, only: [:new]
  end

  get '/courses.json' => redirect('/workshops.json')
  get '/courses/:id' => redirect('/workshops/%{id}')
  resources :workshops, only: [:index, :show] do
    resources :follow_ups, only: [:create]
  end

  resources :products, only: [:index, :show] do
    resources :redemptions, only: [:new]
    resources :stripe_redemptions, only: [:new]
    resources :purchases, only: [:new, :create]
  end
  get '/products/:id/purchases/:lookup' => redirect("/purchases/%{lookup}")

  resources :purchases, only: [:show] do
    resources :videos, only: [:show]
    member do
      get 'paypal'
    end
  end

  namespace :subscriber do
    resources :products, only: [] do
      resources :purchases, only: [:new, :create]
    end
    resources :sections, only: [] do
      resources :purchases, only: [:new, :create]
    end
    resources :invoices, only: [:index, :show]
  end

  resources :subscriptions, only: [:destroy, :update]

  resources :episodes, path: 'podcast', only: [:index, :show]
  get '/podcasts' => redirect("/podcast")
  get '/podcasts/:id' => redirect("/podcast/%{id}")

  resources :design_for_developers_resources, path: 'design-for-developers-resources', only: [:index, :show]
  resources :test_driven_rails_resources, path: 'test-driven-rails-resources', only: [:index]
  get '/d4d-resources' => redirect('/design-for-developers-resources')

  resources :topics, only: :index, path: 'trails'

  resources :bytes, only: [:index, :show]
  get '/articles/:id' => redirect("/bytes/%{id}")

  namespace :reports do
    resource :purchases_charts, only: :show
  end

  get '/auth/:provider/callback', to: 'auth_callbacks#create'

  get "/pages/*id" => 'pages#show', :as => :page, :format => false
  get '/prime' => 'pages#show', as: :prime, id: 'prime'
  get '/sale' => 'pages#show', as: :learnsale, id: 'learnsale'
  get '/watch' => 'pages#show', as: :watch, id: 'watch'
  get '/privacy' => 'pages#show', as: :privacy, id: 'privacy'
  get '/terms' => 'pages#show', as: :terms, id: 'terms'
  get '/directions' => "pages#show", as: :directions, id: "directions"
  get '/group-training' => "pages#show", as: :group_training, id: "group-training"
  get '/humans-present/oss' => "pages#show", as: :humans_present_oss, id: "humans-present-oss"
  get '/backbone-js-on-rails' => redirect("/products/1-backbone-js-on-rails")
  get '/5by5' => redirect('/workshops/19-design-for-developers?utm_source=5by5')
  get '/rubyist-booster-shot' => "pages#show", as: :rubyist_booster_shot, id: "rubyist-booster-shot"

  put '/my_account' => 'users#update', as: 'my_account'
  get '/my_account' => 'users#edit', as: 'my_account'
  get '/sign_up' => 'users#new', as: 'sign_up'
  get '/sign_in' => 'sessions#new', as: 'sign_in'
  resources :users, controller: 'users'
  resources :passwords, controller: 'passwords'

  mount Split::Dashboard, at: 'split'

  mount StripeEvent::Engine, at: 'stripe-webhook'

  resources 'bytes', only: :index

  get ':id' => 'topics#show', as: :topic
  get '/:id/articles' => 'articles#index', as: 'topic_articles'
  get '/:topic_id/bytes' => 'topics/bytes#index', as: 'topic_bytes'
end

app/views/shared/_admin_sign_out.html.erb
<% if signed_in? && current_user.admin? -%>
  <%= link_to('Admin', admin_path) %>
<% end -%>

app/views/shared/_adwords_conversion_tracker.html.erb
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 983769411;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "f5f5f0";
var google_conversion_label = "h6fpCI3R6QkQw8KM1QM";
var google_conversion_value = <%= value %>;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/983769411/?value=<%= value %>&amp;label=h6fpCI3R6QkQw8KM1QM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

app/views/shared/_backbone_checkout_intro.html.erb
<p>Backbone.js on Rails covers intermediate to advanced topics on using Backbone.js and Rails. The book is still in progress – but that's the best part! You get full access to the GitHub repository as we write. In addition to the book, your purchase gets you access to a complete example application, all future updates to the book and example app, and the ability to ask us questions and receive Rails and Backbone.js support via GitHub issues.</p>

app/views/shared/_credit_card_form.html.erb
<li class="subscription-errors"></li>
<li id="purchase_cc_input" class="stripe">
  <label for='card-number'>Card Number</label>
  <input type='text' size='20' autocomplete='off' id='card-number' class='card-number'/>
</li>
<li id="purchase_expiration_input" class="stripe">
  <label>Expiration</label>
  <%= select_month nil, { prompt: 'Month', add_month_numbers: true }, class: 'card-expiry-month' %>
  <%= select_year nil, { prompt: 'Year', start_year: Date.today.year, end_year: 10.years.from_now.year }, class: 'card-expiry-year' %>
</li>
<li id="purchase_cvc_input" class="stripe">
  <label for='card-cvc'>CVC</label>
  <input type='text' size='4' autocomplete='off' id='card-cvc' class='card-cvc'/>
</li>

app/views/shared/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% (flash.keys & [:success, :info, :notice, :error]).each do |key| -%>
      <div class="flash <%= key %>">
        <%= flash[key] %>
      </div>
    <% end -%>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <nav>
    <section id="thoughtbot">
      <ul>
        <% if signed_in? %>
          <li><%= link_to('Sign out', sign_out_path, method: :delete) %></li>
        <% else %>
          <li><%= link_to 'Sign in', sign_in_path %></li>
        <% end %>
      </ul>
      <ul>
        <li><a href="http://thoughtbot.com">About thoughtbot</a></li>
        <li><a href="http://apprentice.io">Apprentice.io</a></li>
        <li><a href="http://thoughtbot.com/podcast">Podcast</a></li>
        <li><%= link_to 'Learn Bytes', bytes_path %></li>
        <li><%= link_to 'Privacy Policy', privacy_path %></li>
        <li><%= link_to 'Terms & Conditions', terms_path %></li>
      </ul>
    </section>

    <section id="trails">
      <ul>
        <li><%= link_to 'Trail Maps', topics_path %></li>
      </ul>
      <ul>
        <% topics.each do |topic| %>
          <li><%= link_to topic.name, topic %></li>
        <% end %>
      </ul>
    </section>
  </nav>

  <p id="copyright">© 2012 - <%= Time.zone.today.year %> thoughtbot, inc. The <em>design of a robot</em> and <em>thoughtbot</em> are registered trademarks of thoughtbot,&nbsp;inc.</p>
  <%= render partial: 'shared/admin_sign_out' %>
</footer>

<%= render "chat" %>

app/views/shared/_google_analytics.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-1485842-14']);
  _gaq.push(['_trackPageview']);

  (function() {
   var ga = document.createElement('script'); ga.type =
   'text/javascript'; ga.async = true;
   ga.src = ('https:' == document.location.protocol ? 'https://ssl' :
     'http://www') + '.google-analytics.com/ga.js';
   var s = document.getElementsByTagName('script')[0];
   s.parentNode.insertBefore(ga, s);
   })();
</script>

app/views/shared/_header.html.erb
<section id="header-wrapper" class="<%= 'subscriber' if current_user_has_active_subscription? %>">
  <div class="header-container">
    <h1 class="small-logo">
      <%= link_to root_path do %>
        <%= image_tag('learn/learn-ralph-small.png') %>
        <span><%= t 'shared.learn' %></span>
      <% end %>
    </h1>
    <nav class="left">
      <ul>
        <% if signed_in? %>
          <li class="back"><%= link_to '&larr; Dashboard'.html_safe, root_url %></li>
        <% else %>
          <li class="toggle-slider"><%= link_to 'View all our products', '#', class: 'toggle-slider' %></li>
        <% end %>
        <%= yield(:additional_header_links) %>
      </ul>
    </nav>
    <nav>
      <ul>
        <% if subscription_product && !current_user_has_active_subscription? %>
          <li class="prime">
            <%= link_to prime_path do %>
              <span><%= t('shared.subscriptions.icon') %></span> <%= subscription_product.name %> Membership
            <% end %>
          </li>
        <% end %>
        <% if signed_in? %>
          <li class="account"><%= link_to 'Settings', my_account_path %></li>
        <% else %>
          <li class="account"><%= link_to 'Sign in', sign_in_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</section>

<% if subscription_product && !current_user_has_active_subscription? && !signed_in? %>
  <section class="products card-slider header">
    <a class="nav prev disabled"></a>
    <%= render partial: 'products/workshop', collection: online_workshops %>
    <%= render partial: 'products/workshop', collection: in_person_workshops %>
    <%= render partial: 'products/video', collection: videos %>
    <%= render partial: 'products/book', collection: books %>
    <a class="nav next"></a>
  </section>
<% end %>

app/views/shared/_javascript.html.erb
<%= javascript_include_tag 'application', 'prefilled_input' %>

<%= render 'shared/kissmetrics' %>

<%= yield :javascript %>

<% if Rails.env.production? %>
  <%= render 'shared/google_analytics' %>
  <script src="//d1nu2rn22elx8m.cloudfront.net/performable/pax/3tbRq2.js" type="text/javascript"></script>
<% end %>

<% unless Rails.env.test? %>
  <script type="text/javascript">
    (function() {
     var st = document.createElement('script'); st.type = 'text/javascript'; st.async = true;
     st.src = 'https://platform.readmill.com/send.js';
     var p = document.getElementsByTagName('script')[0]; p.parentNode.insertBefore(st, p);
     })();
   </script>
<% end %>

<% if Rails.env.test? || Rails.env.cucumber? %>
  <%= javascript_tag do %>
    jQuery.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

<script type="text/javascript">
  <% Split::Experiment.all.each do |experiment| %>
    _kmq.push(['set', { '<%= experiment.name %>': '<%= ab_test(experiment.name, *experiment.alternative_names) %>' }]);
  <% end %>
</script>

app/views/shared/_kissmetrics.html.erb
<%= javascript_tag do %>
  <% Split::Experiment.all.each do |experiment| %>
    <% km.set(experiment.name, ab_test(experiment.name, *experiment.alternative_names)) %>
  <% end %>
<% end %>

<%=raw km.js! %>

app/views/shared/_meta.html.erb
<meta charset="utf-8" />
<title>thoughtbot workshops</title>
<%= stylesheet_link_tag 'admin' %>
<link rel="icon" href="/favicon.ico" type="image/x-icon">
<meta http-equiv="Description" name="Description" content="Workshops to help you get a job as a designer or developer at a web startup." />
<meta http-equiv="Keywords" name="Keywords" content="web designer job, web design job, web development job, startup designer, startup developer, web startup job, startup job" />
<script type="text/javascript" src="http://use.typekit.com/but4fad.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>

app/views/shared/_sidebar_chat.html.erb
<div class="text-chat">
  <h3>Text Chat</h3>
  <hr>
  <p>Every <%= purchaseable.product_type %> includes support for any questions you may have about the topic. Visit our Campfire chat.</p>
  <%= link_to "Join Chat", CHAT_LINK, class: 'button' %>
</div>

app/views/shared/_sidebar_forum.html.erb
<% if current_user_has_active_subscription? %>
  <div class="forum">
    <h3>Forum</h3>
    <hr>
    <p>Your subscription includes support for any questions you may have about the topic.</p>
    <%= link_to "Visit Forums", forum_url, class: 'button' %>
  </div>
<% end %>

app/views/shared/_typekit.html.erb
<% unless Rails.env.test? %>
  <script type="text/javascript" src="//use.typekit.net/jes4mbj.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
<% end %>