config/routes.rb
Workshops::Application.routes.draw do
  use_doorkeeper

  mount RailsAdmin::Engine => '/admin', :as => 'admin'

  root to: 'homes#show'

  get '/api/v1/me.json' => 'api/v1/users#show', as: :resource_owner
  namespace :api do
    namespace :v1 do
      resources :completions, only: [:index, :show, :create, :destroy]
    end
  end

  get '/pages/tmux' => redirect('/products/4-humans-present-tmux')

  if Rails.env.staging? || Rails.env.production?
    get '/products/:id' => redirect('/workshops/18-test-driven-rails'),
      constraints: { id: /(10|12).*/ }
    get '/products/:id' => redirect('/workshops/19-design-for-developers'),
      constraints: { id: /(9|11).*/ }
    get '/products/14' => redirect('/prime')
    get '/products/14-prime' => redirect('/prime')
  end

  resource :session, controller: 'sessions'

  resources :sections, only: [] do
    resources :purchases, only: [:new, :create]
    resources :redemptions, only: [:new]
  end

  get '/courses.json' => redirect('/workshops.json')
  get '/courses/:id' => redirect('/workshops/%{id}')
  resources :workshops, only: [:index, :show] do
    resources :follow_ups, only: [:create]
  end

  resources :products, only: [:index, :show] do
    resources :redemptions, only: [:new]
    resources :stripe_redemptions, only: [:new]
    resources :purchases, only: [:new, :create]
  end
  get '/products/:id/purchases/:lookup' => redirect("/purchases/%{lookup}")

  resources :purchases, only: [:show] do
    resources :videos, only: [:show]
    member do
      get 'paypal'
    end
  end

  namespace :subscriber do
    resources :products, only: [] do
      resources :purchases, only: [:new, :create]
    end
    resources :sections, only: [] do
      resources :purchases, only: [:new, :create]
    end
    resources :invoices, only: [:index, :show]
  end

  resources :subscriptions, only: [:destroy, :update]

  resources :episodes, path: 'podcast', only: [:index, :show]
  get '/podcasts' => redirect("/podcast")
  get '/podcasts/:id' => redirect("/podcast/%{id}")

  resources :design_for_developers_resources, path: 'design-for-developers-resources', only: [:index, :show]
  resources :test_driven_rails_resources, path: 'test-driven-rails-resources', only: [:index]
  get '/d4d-resources' => redirect('/design-for-developers-resources')

  resources :topics, only: :index, path: 'trails'

  resources :bytes, only: [:index, :show]
  get '/articles/:id' => redirect("/bytes/%{id}")

  namespace :reports do
    resource :purchases_charts, only: :show
  end

  get '/auth/:provider/callback', to: 'auth_callbacks#create'

  get "/pages/*id" => 'pages#show', :as => :page, :format => false
  get '/prime' => 'pages#show', as: :prime, id: 'prime'
  get '/sale' => 'pages#show', as: :learnsale, id: 'learnsale'
  get '/watch' => 'pages#show', as: :watch, id: 'watch'
  get '/privacy' => 'pages#show', as: :privacy, id: 'privacy'
  get '/terms' => 'pages#show', as: :terms, id: 'terms'
  get '/directions' => "pages#show", as: :directions, id: "directions"
  get '/group-training' => "pages#show", as: :group_training, id: "group-training"
  get '/humans-present/oss' => "pages#show", as: :humans_present_oss, id: "humans-present-oss"
  get '/backbone-js-on-rails' => redirect("/products/1-backbone-js-on-rails")
  get '/5by5' => redirect('/workshops/19-design-for-developers?utm_source=5by5')
  get '/rubyist-booster-shot' => "pages#show", as: :rubyist_booster_shot, id: "rubyist-booster-shot"

  put '/my_account' => 'users#update', as: 'my_account'
  get '/my_account' => 'users#edit', as: 'my_account'
  get '/sign_up' => 'users#new', as: 'sign_up'
  get '/sign_in' => 'sessions#new', as: 'sign_in'
  resources :users, controller: 'users'
  resources :passwords, controller: 'passwords'

  mount Split::Dashboard, at: 'split'

  mount StripeEvent::Engine, at: 'stripe-webhook'

  resources 'bytes', only: :index

  get ':id' => 'topics#show', as: :topic
  get '/:id/articles' => 'articles#index', as: 'topic_articles'
  get '/:topic_id/bytes' => 'topics/bytes#index', as: 'topic_bytes'
end

app/models/episode.rb
require 'mp3info'
require 'open-uri'

class Episode < ActiveRecord::Base
  attr_accessible :title, :duration, :file, :description, :published_on, :notes,
    :old_url, :file_size, :topic_ids

  has_many :classifications, as: :classifiable
  has_many :topics, through: :classifications
  has_many :products, through: :topics, uniq: true
  has_many :workshops, through: :topics, uniq: true

  validates :title, presence: true
  validates :duration, presence: true
  validates :file, presence: true
  validates :file_size, presence: true
  validates :description, presence: true
  validates :published_on, presence: true

  before_validation :extract_info_from_mp3, on: :create

  def self.published
    where('published_on <= ?', Time.zone.today).order('published_on desc')
  end

  def full_title
    "Episode #{id}: #{title}"
  end

  def rss_pub_date
    published_on.to_s(:rfc822)
  end

  def increment_downloads
    increment!(:downloads_count)
  end

  def related
    @related ||= Related.new(self)
  end

  private

  def extract_info_from_mp3
    if file.present? && title.blank?
      self.file_size = mp3_file.size
      Mp3Info.open(mp3_file) do |mp3|
        extract_tag_info(mp3)
      end
    end
  end

  def mp3_file
    @mp3_file ||= open(file)
  end

  def extract_tag_info(mp3)
    self.title = extract_title(mp3.tag2.TIT2)
    self.description = extract_description(mp3.tag2.TDES)
    self.notes = extract_notes(mp3.tag2.TDES)
    self.published_on = Date.parse(mp3.tag2.TDRL)
    self.duration = mp3.length.to_i
  end

  def extract_title(mp3_title)
    mp3_title.split(':')[1].strip
  end

  def extract_description(mp3_des)
    mp3_des.lines.first.chomp
  end

  def extract_notes(mp3_des)
    mp3_des.split("\n")[1..-1].join("\n")
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def index
    expires_in 1.hour, public: true
    @episodes = Episode.published
    fresh_when(@episodes.first, public: true)
  end

  def show
    @episode = Episode.find(params[:id])
    respond_to do |format|
      format.html
      format.mp3 do
        @episode.increment_downloads
        redirect_to @episode.file
      end
    end
  end
end

app/views/episodes/_credits.html.erb
<section class="credits">
  <p><em>The Giant Robots Smashing into Other Giant Robots podcast is sponsored by <a href="http://thoughtbot.com">thoughtbot</a>, hosted by <a href="http://codeulate.com/">Ben Orenstein</a>, edited by <a href="http://presskit.to/igorstolarsky">Igor Stolarsky</a>, and produced by <a href="http://chadpytel.com/">Chad&nbsp;Pytel</a>.</em></p>
</section>

app/views/episodes/_episode.html.erb
<div class="episode">
  <%= link_to episode do %>
    <hgroup class="post-link-header">
      <h3><%= episode.full_title %></h3>
      <h6 class="info">
        <%= episode.published_on.to_time.to_s(:short_date) %> • <%= distance_of_time_in_words episode.duration %>
      </h6>
    </hgroup>
    <p><%= episode.description %></p>
  <% end %>
</div>

app/views/episodes/_introduction.html.erb
<div class="summary">
  <%= link_to image_tag("podcast/podcastlogo-small.png", class: 'cover', width: 145, height: 145), episodes_path %>

  <p>The Giant Robots Smashing into Other Giant Robots podcast is a weekly technical podcast discussing development, design, and the business of software development.</p>
  <p>Hosted by Ben Orenstein, who is joined each week by developers and designers from thoughtbot and beyond.</p>

  <p class="links">
    <%= link_to "http://itunes.apple.com/us/podcast/giant-robots-smashing-into/id535121941" do %>
      <%= image_tag("podcast/itunes.png", class: 'itunes', width: 12, height: 12) %> Subscribe in iTunes
    <% end %>
    <%= link_to episodes_path(format: :xml) do %>
      <%= image_tag("podcast/rss.png", class: 'rss', width: 12, height: 12) %> Subscribe via RSS
    <% end %>
    <%= link_to "http://stitcher.com/s?fid=31937refid=stpr" do %>
      <%= image_tag("podcast/stitcher.png", class: 'rss', width: 12, height: 12) %> Listen via Stitcher
    <% end %>
  </p>
</div>

app/views/episodes/index.html.erb
<% content_for :subject, t('shared.podcast') %>
<%= render 'introduction' %>

<div class="text-box-wrapper">
  <div class="text-box">
    <hgroup class="product-title">
      <h2>All episodes</h2>
    </hgroup>
    <%= render @episodes %>
  </div>
</div>

<aside>
  <%= render 'credits' %>
</aside>

app/views/episodes/show.html.erb
<% content_for :subject, t('shared.podcast') %>

<%= render 'introduction' %>

<div class="text-box-wrapper">
  <div class="text-box">
    <hgroup class="product-title">
      <h2>Episode #<%= @episode.id %></h1>
      <h3><%= @episode.title %></h2>
    </hgroup>

    <p><%= @episode.description %></p>

    <div class="listen">
      <audio preload="none" controls="controls">
      <source src="<%= episode_path(@episode, format: :mp3) %>" type="audio/mpeg" />
      </audio>
      <%= link_to "Direct Download", episode_path(@episode, format: :mp3) %> (<%= number_to_human_size @episode.file_size, precision: 2 %>, <%= distance_of_time_in_words @episode.duration %>)
    </div>

    <% unless @episode.notes.blank? %>
      <h3>Notes &amp; Links</h3>
      <p class="notes">
      <%== format_podcast_notes @episode.notes %>
      </p>
    <% end %>

    <section id="podcast-questions">
    <h3>To have your questions answered on the air</h3>
    <p>Email your questions to <a href="mailto:info@thoughtbot.com">info@thoughtbot.com</a> or Tweet to us <a href="http://twitter.com/thoughtbot">@thoughtbot</a>.</p>
    </section>
  </div>

  <%= render 'credits' %>
</div>

<%= render @episode.related %>