config/routes.rb
Workshops::Application.routes.draw do
  use_doorkeeper

  mount RailsAdmin::Engine => '/admin', :as => 'admin'

  root to: 'homes#show'

  get '/api/v1/me.json' => 'api/v1/users#show', as: :resource_owner
  namespace :api do
    namespace :v1 do
      resources :completions, only: [:index, :show, :create, :destroy]
    end
  end

  get '/pages/tmux' => redirect('/products/4-humans-present-tmux')

  if Rails.env.staging? || Rails.env.production?
    get '/products/:id' => redirect('/workshops/18-test-driven-rails'),
      constraints: { id: /(10|12).*/ }
    get '/products/:id' => redirect('/workshops/19-design-for-developers'),
      constraints: { id: /(9|11).*/ }
    get '/products/14' => redirect('/prime')
    get '/products/14-prime' => redirect('/prime')
  end

  resource :session, controller: 'sessions'

  resources :sections, only: [] do
    resources :purchases, only: [:new, :create]
    resources :redemptions, only: [:new]
  end

  get '/courses.json' => redirect('/workshops.json')
  get '/courses/:id' => redirect('/workshops/%{id}')
  resources :workshops, only: [:index, :show] do
    resources :follow_ups, only: [:create]
  end

  resources :products, only: [:index, :show] do
    resources :redemptions, only: [:new]
    resources :stripe_redemptions, only: [:new]
    resources :purchases, only: [:new, :create]
  end
  get '/products/:id/purchases/:lookup' => redirect("/purchases/%{lookup}")

  resources :purchases, only: [:show] do
    resources :videos, only: [:show]
    member do
      get 'paypal'
    end
  end

  namespace :subscriber do
    resources :products, only: [] do
      resources :purchases, only: [:new, :create]
    end
    resources :sections, only: [] do
      resources :purchases, only: [:new, :create]
    end
    resources :invoices, only: [:index, :show]
  end

  resources :subscriptions, only: [:destroy, :update]

  resources :episodes, path: 'podcast', only: [:index, :show]
  get '/podcasts' => redirect("/podcast")
  get '/podcasts/:id' => redirect("/podcast/%{id}")

  resources :design_for_developers_resources, path: 'design-for-developers-resources', only: [:index, :show]
  resources :test_driven_rails_resources, path: 'test-driven-rails-resources', only: [:index]
  get '/d4d-resources' => redirect('/design-for-developers-resources')

  resources :topics, only: :index, path: 'trails'

  resources :bytes, only: [:index, :show]
  get '/articles/:id' => redirect("/bytes/%{id}")

  namespace :reports do
    resource :purchases_charts, only: :show
  end

  get '/auth/:provider/callback', to: 'auth_callbacks#create'

  get "/pages/*id" => 'pages#show', :as => :page, :format => false
  get '/prime' => 'pages#show', as: :prime, id: 'prime'
  get '/sale' => 'pages#show', as: :learnsale, id: 'learnsale'
  get '/watch' => 'pages#show', as: :watch, id: 'watch'
  get '/privacy' => 'pages#show', as: :privacy, id: 'privacy'
  get '/terms' => 'pages#show', as: :terms, id: 'terms'
  get '/directions' => "pages#show", as: :directions, id: "directions"
  get '/group-training' => "pages#show", as: :group_training, id: "group-training"
  get '/humans-present/oss' => "pages#show", as: :humans_present_oss, id: "humans-present-oss"
  get '/backbone-js-on-rails' => redirect("/products/1-backbone-js-on-rails")
  get '/5by5' => redirect('/workshops/19-design-for-developers?utm_source=5by5')
  get '/rubyist-booster-shot' => "pages#show", as: :rubyist_booster_shot, id: "rubyist-booster-shot"

  put '/my_account' => 'users#update', as: 'my_account'
  get '/my_account' => 'users#edit', as: 'my_account'
  get '/sign_up' => 'users#new', as: 'sign_up'
  get '/sign_in' => 'sessions#new', as: 'sign_in'
  resources :users, controller: 'users'
  resources :passwords, controller: 'passwords'

  mount Split::Dashboard, at: 'split'

  mount StripeEvent::Engine, at: 'stripe-webhook'

  resources 'bytes', only: :index

  get ':id' => 'topics#show', as: :topic
  get '/:id/articles' => 'articles#index', as: 'topic_articles'
  get '/:topic_id/bytes' => 'topics/bytes#index', as: 'topic_bytes'
end

app/models/subscription.rb
# This class represents a user's subscription to Learn content
class Subscription < ActiveRecord::Base
  MAILING_LIST = 'Active Subscribers'

  belongs_to :user
  delegate :stripe_customer_id, to: :user

  after_create :add_user_to_mailing_list

  def self.deliver_welcome_emails
    recent.each do |subscription|
      Mailer.welcome_to_prime(subscription.user).deliver
    end
  end

  def self.deliver_byte_notifications
    notifier = ByteNotifier.new(subscriber_emails)
    notifier.send_notifications
  end

  def self.paid
    where(paid: true)
  end

  def active?
    deactivated_on.nil?
  end

  def deactivate
    deactivate_subscription_purchases
    remove_user_from_mailing_list
    update_column(:deactivated_on, Time.zone.today)
  end

  private

  def self.subscriber_emails
    active.joins(:user).pluck(:email)
  end

  def self.active
    where(deactivated_on: nil)
  end

  def self.recent
    where('created_at > ?', 24.hours.ago)
  end

  def deactivate_subscription_purchases
    user.subscription_purchases.each do |purchase|
      purchase.refund
    end
  end

  def add_user_to_mailing_list
    MailchimpFulfillmentJob.enqueue(MAILING_LIST, user.email)
  end

  def remove_user_from_mailing_list
    MailchimpRemovalJob.enqueue(MAILING_LIST, user.email)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def destroy
    unsubscriber = Unsubscriber.new(current_user.subscription)
    unsubscriber.schedule
    redirect_to my_account_path
  end

  def update
    customer = Stripe::Customer.retrieve(current_user.stripe_customer_id)
    customer.card = params['stripe_token']
    begin
      customer.save
      redirect_to my_account_path, notice: I18n.t('subscriptions.flashes.update.success')
    rescue Stripe::CardError => error
      redirect_to my_account_path, notice: error.message
    end
  end
end

app/views/subscriptions/_aside.html.erb
<aside>
  <%= render 'shared/sidebar_forum', purchaseable: purchaseable %>
</aside>

app/views/subscriptions/_subscription.html.erb
<li class="subscription">
  <% if subscription.active? %>
    Active since <%= subscription.created_at.to_s(:simple) %>.
    <% if subscription.scheduled_for_cancelation_on %>
      Scheduled for cancelation on <%= subscription.scheduled_for_cancelation_on.to_s(:simple) %>.
    <% end %>
  <% else %>
    Canceled on <%= subscription.deactivated_on.to_s(:simple) %>
  <% end %>

  <%= link_to 'View all invoices', subscriber_invoices_path, class: 'invoices' %>
  <% if subscription.active? && subscription.scheduled_for_cancelation_on.blank? %>
    <%= link_to t('subscriptions.cancel'), subscription,
      method: :delete,
      confirm: "Are you sure you want to cancel your Prime subscription? You will lose access to the products you acquired through Prime, as well as the forum and Learn Bytes at the end of your billing cycle.",
      class: 'cancel'
    %>
  <% end %>
</li>

app/views/subscriptions/subscription_purchase_show.html.erb
<% content_for :subject, @purchaseable.name %>
<%= adwords_conversion_tracker(flash[:purchase_paid_price]) %>

<div class="text-box-wrapper">
  <div class="text-box">
    <p>Thank you for purchasing <%= @purchaseable.name %>.</p>

    <% if current_user.inactive_subscription %>
      <p>You stopped subscribing to <%= @purchaseable.name %> on
      <%= current_user.inactive_subscription.deactivated_on.to_s(:long) %>. If you would like
      to resubscribe, please <%= mail_to 'learn@thoughtbot.com', 'contact us' %>.</p>
    <% end %>
  </div>
</div>

<%= render 'subscriptions/aside', purchaseable: @purchaseable, purchase: @purchase %>